name: Build and upload image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm ci
      - name: Build React project
        run: npm run build
        env:
          REACT_APP_BACKEND_BASE_URL: ${{ secrets.BACKEND_BASE_URL }}
      - name: Build Docker image and submit to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: fgai4htgsymptom/mmvb-frontend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest,${{ github.sha }}
