name: Build and upload image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Docker image and submit to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@2.21
        env:
          REACT_APP_BACKEND_BASE_URL: ${{ secrets.BACKEND_BASE_URL }}
        with:
          name: fgai4htgsymptom/mmvb-frontend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest,${{ github.sha }}
          buildargs: REACT_APP_BACKEND_BASE_URL
